// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJMK9JsjZ90MujVP-o7qdRwpTlBY_TRPU',
    appId: '1:108399767879:web:6df5547fcb083e5dccdc62',
    messagingSenderId: '108399767879',
    projectId: 'new-app-59374',
    authDomain: 'new-app-59374.firebaseapp.com',
    storageBucket: 'new-app-59374.firebasestorage.app',
    measurementId: 'G-V1YFLMV2H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp00wbFRRWNGdkuuonLxayBpLmbL-w3o8',
    appId: '1:108399767879:android:5257683f791eef69ccdc62',
    messagingSenderId: '108399767879',
    projectId: 'new-app-59374',
    storageBucket: 'new-app-59374.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_POlQAq3Uv28fznU0qxsPdrl9T_BZJIs',
    appId: '1:108399767879:ios:3fb0be92151af392ccdc62',
    messagingSenderId: '108399767879',
    projectId: 'new-app-59374',
    storageBucket: 'new-app-59374.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_POlQAq3Uv28fznU0qxsPdrl9T_BZJIs',
    appId: '1:108399767879:ios:3fb0be92151af392ccdc62',
    messagingSenderId: '108399767879',
    projectId: 'new-app-59374',
    storageBucket: 'new-app-59374.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJMK9JsjZ90MujVP-o7qdRwpTlBY_TRPU',
    appId: '1:108399767879:web:5259bfd8c2c002caccdc62',
    messagingSenderId: '108399767879',
    projectId: 'new-app-59374',
    authDomain: 'new-app-59374.firebaseapp.com',
    storageBucket: 'new-app-59374.firebasestorage.app',
    measurementId: 'G-PBBFME1JHL',
  );
}
